### ISSUE TITLE
Admin Panel Error 500

### ISSUE THREAD

**Issue by RobbyV2** [Ballsdex-Team/BallsDex-DiscordBot#134]
FYI: It worked fine before, but after pulling the latest changes since June 15th, I'm getting this error.
The bot works fine but viewing the current balls specifically (not ball instance) gives me an error.

```bash
basisballsdex-admin-panel-1      | INFO:     192.168.5.169:64943 - "GET /ball/list HTTP/1.1" 500 Internal Server Error
basisballsdex-admin-panel-1      | ERROR:    Exception in ASGI application
basisballsdex-admin-panel-1      | Traceback (most recent call last):
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
basisballsdex-admin-panel-1      |     result = await app(  # type: ignore[func-returns-value]
basisballsdex-admin-panel-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
basisballsdex-admin-panel-1      |     return await self.app(scope, receive, send)
basisballsdex-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
basisballsdex-admin-panel-1      |     await super().__call__(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
basisballsdex-admin-panel-1      |     await self.middleware_stack(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
basisballsdex-admin-panel-1      |     raise exc
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, _send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
basisballsdex-admin-panel-1      |     raise exc
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, sender)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
basisballsdex-admin-panel-1      |     raise e
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
basisballsdex-admin-panel-1      |     await route.handle(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
basisballsdex-admin-panel-1      |     await self.app(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
basisballsdex-admin-panel-1      |     await super().__call__(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
basisballsdex-admin-panel-1      |     await self.middleware_stack(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
basisballsdex-admin-panel-1      |     raise exc
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, _send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
basisballsdex-admin-panel-1      |     response = await self.dispatch_func(request, call_next)
basisballsdex-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/providers/login.py", line 135, in authenticate
basisballsdex-admin-panel-1      |     response = await call_next(request)
basisballsdex-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
basisballsdex-admin-panel-1      |     raise app_exc
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
basisballsdex-admin-panel-1      |     await self.app(scope, receive_or_disconnect, send_no_error)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
basisballsdex-admin-panel-1      |     response = await self.dispatch_func(request, call_next)
basisballsdex-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/middlewares.py", line 19, in language_processor
basisballsdex-admin-panel-1      |     response = await call_next(request)
basisballsdex-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
basisballsdex-admin-panel-1      |     raise app_exc
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
basisballsdex-admin-panel-1      |     await self.app(scope, receive_or_disconnect, send_no_error)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
basisballsdex-admin-panel-1      |     raise exc
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, sender)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
basisballsdex-admin-panel-1      |     raise e
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
basisballsdex-admin-panel-1      |     await self.app(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
basisballsdex-admin-panel-1      |     await route.handle(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
basisballsdex-admin-panel-1      |     await self.app(scope, receive, send)
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
basisballsdex-admin-panel-1      |     response = await func(request)
basisballsdex-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
basisballsdex-admin-panel-1      |     raw_response = await run_endpoint_function(
basisballsdex-admin-panel-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
basisballsdex-admin-panel-1      |     return await dependant.call(**values)
basisballsdex-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/routes/resources.py", line 34, in list_view
basisballsdex-admin-panel-1      |     filters = await model_resource.get_filters(request, params)
basisballsdex-admin-panel-1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/resources.py", line 198, in get_filters
basisballsdex-admin-panel-1      |     ret.append(await f.render(request, value))
basisballsdex-admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/widgets/filters.py", line 170, in render
basisballsdex-admin-panel-1      |     return await super().render(request, value)
basisballsdex-admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/widgets/filters.py", line 118, in render
basisballsdex-admin-panel-1      |     options = await self.get_options()
basisballsdex-admin-panel-1      |               ^^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/widgets/filters.py", line 152, in get_options
basisballsdex-admin-panel-1      |     ret = await self.get_models()
basisballsdex-admin-panel-1      |           ^^^^^^^^^^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/widgets/filters.py", line 165, in get_models
basisballsdex-admin-panel-1      |     return await self.model.all()
basisballsdex-admin-panel-1      |                  ^^^^^^^^^^^^^^
basisballsdex-admin-panel-1      |   File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
basisballsdex-admin-panel-1      |     raise AttributeError(name) from None
basisballsdex-admin-panel-1      | AttributeError: all
```

Thank you for your work on the bot! Its allowed me to connect with my friends more 😊

**Comment by laggron42** [comment]
That's interesting, have you edited the code maybe? For instance the name of some classes

**Comment by RobbyV2** [comment]
I modified the the regime and economy structure before you added the commit for dynamic ones, so I skipped pulling the changes from that one.

**Comment by laggron42** [comment]
That's an interesting fork you have! I don't help with heavy changes normally, but I still tried to dig in. In [this line](https://github.com/RobbyV2/BASISBallsdex/blob/ebdf320511bef81e7b2ca0f00a7249560e487c03/ballsdex/core/admin/resources.py#L159) you added an `=` sign that transforms the model into a boolean, remove that and you're good.

Next time you have issues with your own changes, don't open an issue and ask me in the dedicated server instead, which you can find in the readme.
