### ISSUE TITLE
Can't start the bot.

### ISSUE THREAD

**Issue by qworrrty** [Ballsdex-Team/BallsDex-DiscordBot#135]
When I enter docker compose up -d, all containers start up but ballsdex-discordbot-master-bot-1 doesn't start. 
------------------- RecDex bot -------------------
2023-08-01 11:03:11                Collect countryballs               
2023-08-01 11:03:11           Discord bot made by El Laggron          
2023-08-01 11:03:11 
2023-08-01 11:03:11  Bot version:              2.7.0
2023-08-01 11:03:11  Discord.py version:       2.3.0
2023-08-01 11:03:11 
2023-08-01 11:03:11 2023-08-01 08:03:11 ERROR    ballsdex Failed to connect to database.
2023-08-01 11:03:11 Traceback (most recent call last):
2023-08-01 11:03:11   File "/code/ballsdex/__main__.py", line 297, in main
2023-08-01 11:03:11     loop.run_until_complete(init_tortoise(db_url))
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
2023-08-01 11:03:11     return future.result()
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/code/ballsdex/__main__.py", line 242, in init_tortoise
2023-08-01 11:03:11     await command.init()
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/aerich/__init__.py", line 38, in init
2023-08-01 11:03:11     await Migrate.init(self.tortoise_config, self.app, self.location)
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/aerich/migrate.py", line 69, in init
2023-08-01 11:03:11     last_version = await cls.get_last_version()
2023-08-01 11:03:11                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/aerich/migrate.py", line 55, in get_last_version
2023-08-01 11:03:11     return await Aerich.filter(app=cls.app).first()
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/queryset.py", line 1008, in _execute
2023-08-01 11:03:11     instance_list = await self._db.executor_class(
2023-08-01 11:03:11                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 131, in execute_select
2023-08-01 11:03:11     _, raw_results = await self.db.execute_query(query.get_sql())
2023-08-01 11:03:11                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
2023-08-01 11:03:11     return await self._translate_exceptions(func, *args, **kwargs)
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
2023-08-01 11:03:11     return await func(self, *args, **kwargs)
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 129, in execute_query
2023-08-01 11:03:11     async with self.acquire_connection() as connection:
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 326, in __aenter__
2023-08-01 11:03:11     await self.ensure_connection()
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/client.py", line 322, in ensure_connection
2023-08-01 11:03:11     await self.client.create_connection(with_db=True)
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
2023-08-01 11:03:11     self._pool = await self.create_pool(password=self.password, **self._template)
2023-08-01 11:03:11                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/asyncpg/client.py", line 65, in create_pool
2023-08-01 11:03:11     return await asyncpg.create_pool(None, **kwargs)
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 409, in _async__init__
2023-08-01 11:03:11     await self._initialize()
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 437, in _initialize
2023-08-01 11:03:11     await first_ch.connect()
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 129, in connect
2023-08-01 11:03:11     self._con = await self._pool._get_new_connection()
2023-08-01 11:03:11                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 507, in _get_new_connection
2023-08-01 11:03:11     con = await connection.connect(
2023-08-01 11:03:11           ^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 2092, in connect
2023-08-01 11:03:11     return await connect_utils._connect(
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 881, in _connect
2023-08-01 11:03:11     return await _connect_addr(
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 773, in _connect_addr
2023-08-01 11:03:11     return await __connect_addr(params, timeout, True, *args)
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py", line 831, in __connect_addr
2023-08-01 11:03:11     await compat.wait_for(connected, timeout=timeout)
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/site-packages/asyncpg/compat.py", line 56, in wait_for
2023-08-01 11:03:11     return await asyncio.wait_for(fut, timeout)
2023-08-01 11:03:11            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-01 11:03:11   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
2023-08-01 11:03:11     return fut.result()
2023-08-01 11:03:11            ^^^^^^^^^^^^
2023-08-01 11:03:11 asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "ballsdex"
2023-08-01 11:03:11 2023-08-01 08:03:11 INFO     tortoise Tortoise-ORM shutdown
This is log.

**Comment by laggron42** [comment]
Can you join the support server found in the readme and ask for help here? Will need more details
