### ISSUE TITLE
i was trying to  make a ball and it said this: . i have no idea what this means. it just refuses to do it

### ISSUE THREAD

**Issue by SevconFactsYoutube** [Ballsdex-Team/BallsDex-DiscordBot#322]
2024-08-03 11:22:47 admin-panel-1      | INFO:     172.18.0.1:36818 - "GET /admin HTTP/1.1" 307 Temporary Redirect
2024-08-03 11:22:47 admin-panel-1      | INFO:     172.18.0.1:36818 - "GET /admin/ HTTP/1.1" 200 OK
2024-08-03 11:22:53 admin-panel-1      | INFO:     172.18.0.1:36822 - "GET /admin/ball/list HTTP/1.1" 200 OK
2024-08-03 11:23:00 admin-panel-1      | INFO:     172.18.0.1:36828 - "GET /admin/ball/create HTTP/1.1" 200 OK
2024-08-03 11:24:13 admin-panel-1      | INFO:     172.18.0.1:47556 - "POST /admin/ball/create HTTP/1.1" 500 Internal Server Error
2024-08-03 11:24:13 admin-panel-1      | ERROR:    Exception in ASGI application
2024-08-03 11:24:13 admin-panel-1      |   + Exception Group Traceback (most recent call last):
2024-08-03 11:24:13 admin-panel-1      |   |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
2024-08-03 11:24:13 admin-panel-1      |   |     yield
2024-08-03 11:24:13 admin-panel-1      |   |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 190, in __call__
2024-08-03 11:24:13 admin-panel-1      |   |     async with anyio.create_task_group() as task_group:
2024-08-03 11:24:13 admin-panel-1      |   |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-08-03 11:24:13 admin-panel-1      |   |     raise BaseExceptionGroup(
2024-08-03 11:24:13 admin-panel-1      |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-08-03 11:24:13 admin-panel-1      |   +-+---------------- 1 ----------------
2024-08-03 11:24:13 admin-panel-1      |     | Traceback (most recent call last):
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-08-03 11:24:13 admin-panel-1      |     |     result = await app(  # type: ignore[func-returns-value]
2024-08-03 11:24:13 admin-panel-1      |     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     return await self.app(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await super().__call__(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive, _send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 11:24:13 admin-panel-1      |     |     await app(scope, receive, sender)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
2024-08-03 11:24:13 admin-panel-1      |     |     await route.handle(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 487, in handle
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await super().__call__(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive, _send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     with collapse_excgroups():
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-08-03 11:24:13 admin-panel-1      |     |     self.gen.throw(typ, value, traceback)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     response = await self.dispatch_func(request, call_next)
2024-08-03 11:24:13 admin-panel-1      |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/providers/login.py", line 135, in authenticate
2024-08-03 11:24:13 admin-panel-1      |     |     response = await call_next(request)
2024-08-03 11:24:13 admin-panel-1      |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-08-03 11:24:13 admin-panel-1      |     |     raise app_exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive_or_disconnect, send_no_error)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     with collapse_excgroups():
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-08-03 11:24:13 admin-panel-1      |     |     self.gen.throw(typ, value, traceback)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     response = await self.dispatch_func(request, call_next)
2024-08-03 11:24:13 admin-panel-1      |     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/middlewares.py", line 19, in language_processor
2024-08-03 11:24:13 admin-panel-1      |     |     response = await call_next(request)
2024-08-03 11:24:13 admin-panel-1      |     |                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-08-03 11:24:13 admin-panel-1      |     |     raise app_exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive_or_disconnect, send_no_error)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 11:24:13 admin-panel-1      |     |     await app(scope, receive, sender)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
2024-08-03 11:24:13 admin-panel-1      |     |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
2024-08-03 11:24:13 admin-panel-1      |     |     await route.handle(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
2024-08-03 11:24:13 admin-panel-1      |     |     await self.app(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
2024-08-03 11:24:13 admin-panel-1      |     |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 11:24:13 admin-panel-1      |     |     raise exc
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 11:24:13 admin-panel-1      |     |     await app(scope, receive, sender)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
2024-08-03 11:24:13 admin-panel-1      |     |     response = await func(request)
2024-08-03 11:24:13 admin-panel-1      |     |                ^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
2024-08-03 11:24:13 admin-panel-1      |     |     raise e
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
2024-08-03 11:24:13 admin-panel-1      |     |     raw_response = await run_endpoint_function(
2024-08-03 11:24:13 admin-panel-1      |     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-08-03 11:24:13 admin-panel-1      |     |     return await dependant.call(**values)
2024-08-03 11:24:13 admin-panel-1      |     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/routes/resources.py", line 227, in create
2024-08-03 11:24:13 admin-panel-1      |     |     obj = await model.create(**data, using_db=conn)
2024-08-03 11:24:13 admin-panel-1      |     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/tortoise/models.py", line 1136, in create
2024-08-03 11:24:13 admin-panel-1      |     |     await instance.save(using_db=db, force_create=True)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/tortoise/models.py", line 944, in save
2024-08-03 11:24:13 admin-panel-1      |     |     await executor.execute_insert(self)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 223, in execute_insert
2024-08-03 11:24:13 admin-panel-1      |     |     values = [
2024-08-03 11:24:13 admin-panel-1      |     |              ^
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 224, in <listcomp>
2024-08-03 11:24:13 admin-panel-1      |     |     self.column_map[field_name](getattr(instance, field_name), instance)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/tortoise/fields/base.py", line 232, in to_db_value
2024-08-03 11:24:13 admin-panel-1      |     |     self.validate(value)
2024-08-03 11:24:13 admin-panel-1      |     |   File "/usr/local/lib/python3.11/site-packages/tortoise/fields/base.py", line 262, in validate
2024-08-03 11:24:13 admin-panel-1      |     |     raise ValidationError(f"{self.model_field_name}: {exc}")
2024-08-03 11:24:13 admin-panel-1      |     | tortoise.exceptions.ValidationError: wild_card: Value must not be None
2024-08-03 11:24:13 admin-panel-1      |     +------------------------------------
2024-08-03 11:24:13 admin-panel-1      | 
2024-08-03 11:24:13 admin-panel-1      | During handling of the above exception, another exception occurred:
2024-08-03 11:24:13 admin-panel-1      | 
2024-08-03 11:24:13 admin-panel-1      | Traceback (most recent call last):
2024-08-03 11:24:13 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-08-03 11:24:13 admin-panel-1      |     result = await app(  # type: ignore[func-returns-value]
2024-08-03 11:24:13 admin-panel-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-08-03 11:24:13 admin-panel-1      |     return await self.app(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:13 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-08-03 11:24:13 admin-panel-1      |     await super().__call__(scope, receive, send)
2024-08-03 11:24:13 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-08-03 11:24:13 admin-panel-1      |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive, _send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await self.simple_response(scope, receive, send, request_headers=headers)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 11:24:14 admin-panel-1      |     await app(scope, receive, sender)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
2024-08-03 11:24:14 admin-panel-1      |     await route.handle(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 487, in handle
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await super().__call__(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive, _send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-08-03 11:24:14 admin-panel-1      |     with collapse_excgroups():
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-08-03 11:24:14 admin-panel-1      |     self.gen.throw(typ, value, traceback)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-08-03 11:24:14 admin-panel-1      |     response = await self.dispatch_func(request, call_next)
2024-08-03 11:24:14 admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/providers/login.py", line 135, in authenticate
2024-08-03 11:24:14 admin-panel-1      |     response = await call_next(request)
2024-08-03 11:24:14 admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-08-03 11:24:14 admin-panel-1      |     raise app_exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive_or_disconnect, send_no_error)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-08-03 11:24:14 admin-panel-1      |     with collapse_excgroups():
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
2024-08-03 11:24:14 admin-panel-1      |     self.gen.throw(typ, value, traceback)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
2024-08-03 11:24:14 admin-panel-1      |     response = await self.dispatch_func(request, call_next)
2024-08-03 11:24:14 admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/middlewares.py", line 19, in language_processor
2024-08-03 11:24:14 admin-panel-1      |     response = await call_next(request)
2024-08-03 11:24:14 admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
2024-08-03 11:24:14 admin-panel-1      |     raise app_exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive_or_disconnect, send_no_error)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 11:24:14 admin-panel-1      |     await app(scope, receive, sender)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
2024-08-03 11:24:14 admin-panel-1      |     await self.middleware_stack(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
2024-08-03 11:24:14 admin-panel-1      |     await route.handle(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
2024-08-03 11:24:14 admin-panel-1      |     await self.app(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
2024-08-03 11:24:14 admin-panel-1      |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-08-03 11:24:14 admin-panel-1      |     raise exc
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-08-03 11:24:14 admin-panel-1      |     await app(scope, receive, sender)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
2024-08-03 11:24:14 admin-panel-1      |     response = await func(request)
2024-08-03 11:24:14 admin-panel-1      |                ^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
2024-08-03 11:24:14 admin-panel-1      |     raise e
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
2024-08-03 11:24:14 admin-panel-1      |     raw_response = await run_endpoint_function(
2024-08-03 11:24:14 admin-panel-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-08-03 11:24:14 admin-panel-1      |     return await dependant.call(**values)
2024-08-03 11:24:14 admin-panel-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/fastapi_admin/routes/resources.py", line 227, in create
2024-08-03 11:24:14 admin-panel-1      |     obj = await model.create(**data, using_db=conn)
2024-08-03 11:24:14 admin-panel-1      |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/models.py", line 1136, in create
2024-08-03 11:24:14 admin-panel-1      |     await instance.save(using_db=db, force_create=True)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/models.py", line 944, in save
2024-08-03 11:24:14 admin-panel-1      |     await executor.execute_insert(self)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 223, in execute_insert
2024-08-03 11:24:14 admin-panel-1      |     values = [
2024-08-03 11:24:14 admin-panel-1      |              ^
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/backends/base/executor.py", line 224, in <listcomp>
2024-08-03 11:24:14 admin-panel-1      |     self.column_map[field_name](getattr(instance, field_name), instance)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/fields/base.py", line 232, in to_db_value
2024-08-03 11:24:14 admin-panel-1      |     self.validate(value)
2024-08-03 11:24:14 admin-panel-1      |   File "/usr/local/lib/python3.11/site-packages/tortoise/fields/base.py", line 262, in validate
2024-08-03 11:24:14 admin-panel-1      |     raise ValidationError(f"{self.model_field_name}: {exc}")
2024-08-03 11:24:14 admin-panel-1      | tortoise.exceptions.ValidationError: wild_card: Value must not be None

**Comment by imtherealF1** [comment]
@SevconFactsYoutube you didn't insert a wild card, wild card = spawn art. put an image that you want in that field, and then you won't get that issue

**Comment by SevconFactsYoutube** [comment]
it aint doin it @imtherealF1 

Uploading huh.mp4…

**Comment by SevconFactsYoutube** [comment]
the issue is also in special events

**Comment by SevconFactsYoutube** [comment]
nvm its not
