### ISSUE TITLE
| asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "ballsdex"

### ISSUE THREAD

**Issue by parsakhk** [Ballsdex-Team/BallsDex-DiscordBot#96]
I had created a ballsdex bot called province dex and when i run docker compose up
it says this

```
provincedex-postgres-db-1      |
provincedex-postgres-db-1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
provincedex-postgres-db-1      |
provincedex-postgres-db-1      | 2023-05-24 19:25:30.502 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
provincedex-postgres-db-1      | 2023-05-24 19:25:30.502 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
provincedex-postgres-db-1      | 2023-05-24 19:25:30.502 UTC [1] LOG:  listening on IPv6 address "::", port 5432
provincedex-postgres-db-1      | 2023-05-24 19:25:30.508 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
provincedex-postgres-db-1      | 2023-05-24 19:25:30.514 UTC [29] LOG:  database system was shut down at 2023-05-24 19:25:27 UTC
provincedex-postgres-db-1      | 2023-05-24 19:25:30.519 UTC [1] LOG:  database system is ready to accept connections
provincedex-postgres-backup-1  | 2023/05/24 19:25:33 Running version: v0.0.10
provincedex-postgres-backup-1  | 2023/05/24 19:25:33 new cron: @daily
provincedex-postgres-backup-1  | 2023/05/24 19:25:33 Opening port 3928 for health checking
provincedex-bot-1              | Skipping virtualenv creation, as specified in config file.
provincedex-admin-panel-1      | Skipping virtualenv creation, as specified in config file.
provincedex-bot-1              | ------------------ BallsDex bot ------------------
provincedex-bot-1              |                Collect countryballs
provincedex-bot-1              |           Discord bot made by El Laggron
provincedex-bot-1              |
provincedex-bot-1              |  Bot version:              1.3.9
provincedex-bot-1              |  Discord.py version:       2.0.1
provincedex-bot-1              |
provincedex-postgres-db-1      | 2023-05-24 19:25:34.408 UTC [33] FATAL:  password authentication failed for user "ballsdex"
provincedex-postgres-db-1      | 2023-05-24 19:25:34.408 UTC [33] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
provincedex-bot-1              | [2023-05-24 19:25:34] CRITICAL ballsdex: Unhandled exception.
provincedex-bot-1              | Traceback (most recent call last):
provincedex-bot-1              |   File "/code/ballsdex/__main__.py", line 189, in main
provincedex-bot-1              |     loop.run_until_complete(init_tortoise(db_url))
provincedex-bot-1              |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
provincedex-bot-1              |     return future.result()
provincedex-bot-1              |   File "/code/ballsdex/__main__.py", line 149, in init_tortoise
provincedex-bot-1              |     await command.init()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/aerich/__init__.py", line 38, in init
provincedex-bot-1              |     await Migrate.init(self.tortoise_config, self.app, self.location)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/aerich/migrate.py", line 69, in init
provincedex-bot-1              |     last_version = await cls.get_last_version()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/aerich/migrate.py", line 55, in get_last_version
provincedex-bot-1              |     return await Aerich.filter(app=cls.app).first()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 1006, in _execute
provincedex-bot-1              |     instance_list = await self._db.executor_class(
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/executor.py", line 130, in execute_select
provincedex-bot-1              |     _, raw_results = await self.db.execute_query(query.get_sql())
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base_postgres/client.py", line 34, in _translate_exceptions
provincedex-bot-1              |     return await self._translate_exceptions(func, *args, **kwargs)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 82, in _translate_exceptions
provincedex-bot-1              |     return await func(self, *args, **kwargs)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 129, in execute_query
provincedex-bot-1              |     async with self.acquire_connection() as connection:
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 326, in __aenter__
provincedex-bot-1              |     await self.ensure_connection()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/base/client.py", line 322, in ensure_connection
provincedex-bot-1              |     await self.client.create_connection(with_db=True)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 59, in create_connection
provincedex-bot-1              |     self._pool = await self.create_pool(password=self.password, **self._template)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/tortoise/backends/asyncpg/client.py", line 65, in create_pool
provincedex-bot-1              |     return await asyncpg.create_pool(None, **kwargs)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 413, in _async__init__
provincedex-bot-1              |     await self._initialize()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 441, in _initialize
provincedex-bot-1              |     await first_ch.connect()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 133, in connect
provincedex-bot-1              |     self._con = await self._pool._get_new_connection()
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/pool.py", line 511, in _get_new_connection
provincedex-bot-1              |     con = await connection.connect(
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connection.py", line 2093, in connect
provincedex-bot-1              |     return await connect_utils._connect(
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 889, in _connect
provincedex-bot-1              |     return await _connect_addr(
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 781, in _connect_addr
provincedex-bot-1              |     return await __connect_addr(params, timeout, True, *args)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 839, in __connect_addr
provincedex-bot-1              |     await compat.wait_for(connected, timeout=timeout)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/site-packages/asyncpg/compat.py", line 66, in wait_for
provincedex-bot-1              |     return await asyncio.wait_for(fut, timeout)
provincedex-bot-1              |   File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
provincedex-bot-1              |     return fut.result()
provincedex-bot-1              | asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "ballsdex"
provincedex-bot-1              | [2023-05-24 19:25:34] INFO tortoise: Tortoise-ORM shutdown
provincedex-bot-1 exited with code 1
provincedex-admin-panel-1      | INFO:     Started server process [1]
provincedex-admin-panel-1      | INFO:     Waiting for application startup.
provincedex-admin-panel-1      | INFO:     Application startup complete.
provincedex-admin-panel-1      | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

pls help

**Comment by flaree** [comment]
Join the self hosted server here: https://discord.gg/M4gVaRrRDe

We no longer support self hosting, someone may help you with your issue here if they know how.
